### ISSUE TITLE
Differences between bindings

### ISSUE THREAD

**Issue by Akselmo** [ryupold/raylib.zig#7]
Hi, I'm not new to Raylib but I am new to Zig.

I just would like to know what's the difference between these bindings and https://github.com/Not-Nik/raylib-zig ?

**Comment by ryupold** [comment]
Hey, good question.
I'm also relatively new to Zig and made this bindings as part of learning the language and its build system.

One difference is that I use raylib_parser to generate an intermediate representation as JSON and the generate the Zig/C code from that.
This has 3 benefits for me:
 - This bindings don't have python as dependency and I can do everything with Zig
 - The parser is maintained by raylib and part of its repository
 - I can fine tune specific function signatures to be more idiomatic with zig (like passing slices and enums instead of ints or pointers as arguments)

I tried https://github.com/Not-Nik/raylib-zig and it worked on Windows but I could not manage to get it working with [WebAssembly builds](https://github.com/Not-Nik/raylib-zig#technical-restrictions). 

The only [workaround](https://github.com/ryupold/raylib.zig#webgl-emscripten-builds) I came up with to solve that problem with passing and returning structs to/from the functions, was to generate a set of C functions that do the unwrapping from pointers to structs but on the C side. Because that side is compiled with emcc and can handle it magically.

**Comment by Akselmo** [comment]
Okay, good to know. I may use your bindings for a gamejam if thats ok :) I've been wanting to learn Zig so it seems like perfect excuse, heh.

**Comment by ryupold** [comment]
Sure it's ok, glad if this projects actually helps people :)
I used them for a Ludum Dare jam last year and it was nice to build and upload something in a couple of seconds.

**Comment by Akselmo** [comment]
Sweet, i will have to see near the jam. Im joining Nokiajam in case you are curious. Working with a lower level language for it just makes sense to me :D

**Comment by Akselmo** [comment]
Oh yeah another thing: Maybe you could collab with the other bindings repo? Having one dedicated place for raylib-zig bindings would make things easier for everyone i hope :)

**Comment by ryupold** [comment]
I think the other bindings repo has a different focus for the bindings. I try to be as type safe as possible by wrapping the C functions with idomatic interfaces, to have a nicer experience writing raylib code. While they utilize zigs ability to link directly to C code for raw performance.

**Comment by Akselmo** [comment]
Ahh ok, makes sense. Thanks for clarifying.
